### ISSUE TITLE
Thoughts on improvement

### ISSUE THREAD

**Issue by pariz** [tobega/aoc2019#1]
https://github.com/tobega/aoc2019/blob/d9ad49711dba18a0f4789c1da1fe40e240fd8bd0/a2.tt#L16
https://github.com/tobega/aoc2019/blob/d9ad49711dba18a0f4789c1da1fe40e240fd8bd0/a2.tt#L23

Isn't there a way to pattern match both `<?($@($) <=1>)>` and `<?($@($) <=2>)>`?

**Comment by tobega** [comment]
Well, you could write <=1|=2> (or in older, maybe deprecated syntax, <1|2>)

Not sure it helps, because you still need to check again to do different
operations
